-- RaceBest upcoming running races scraped from https://racebest.com/races
-- on 2026-09-16. Running events only. Skips virtual, bike, triathlon,
-- junior/fun-run novelties, and races already in public.races.
-- Does not delete existing rows.

insert into public.races (
  id, date, name, distances, category, location, postcode, region, status, sources, near_york, country, series
) values
(
  '2026-09-20-bronte-half',
  '2026-09-20',
  'Bronte Half Marathon and 10k',
  array['Half','10K'],
  'trail',
  'Oxenhope',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/xvxvu'],
  true,
  'GB',
  null
),
(
  '2026-09-26-rombalds-romp',
  '2026-09-26',
  'Rombalds Romp',
  array['13K'],
  'fell',
  'Ilkley',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/96vz6'],
  true,
  'GB',
  null
),
(
  '2026-09-27-crag-rat-run',
  '2026-09-27',
  'Knaresborough Crag Rat Run',
  array['5 mile'],
  'trail',
  'Knaresborough',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/frqz2'],
  true,
  'GB',
  null
),
(
  '2026-10-11-grewelthorpe-gmtr',
  '2026-10-11',
  'Grewelthorpe Multi Terrain Race',
  array['13K'],
  'trail',
  'Grewelthorpe',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/azhts'],
  true,
  'GB',
  null
),
(
  '2026-10-28-leeds-5k-oct',
  '2026-10-28',
  'Leeds 5K',
  array['5K'],
  'road',
  'Leeds',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/xt975'],
  true,
  'GB',
  null
),
(
  '2026-11-08-run-bolton-abbey',
  '2026-11-08',
  'Run Bolton Abbey',
  array['Half','10K','5K'],
  'trail',
  'Bolton Abbey',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/gwcry'],
  true,
  'GB',
  null
),
(
  '2026-11-22-clowne-half',
  '2026-11-22',
  'Clowne Half Marathon',
  array['Half'],
  'road',
  'Clowne',
  '',
  'Midlands',
  'listed',
  array['racebest','https://racebest.com/races/2s98u'],
  false,
  'GB',
  null
),
(
  '2026-11-22-tadcaster-10',
  '2026-11-22',
  'Tadcaster 10',
  array['10 mile'],
  'road',
  'Tadcaster',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/e6z7h'],
  true,
  'GB',
  null
),
(
  '2026-11-22-gavin-duffy-5k',
  '2026-11-22',
  'Gavin Duffy Memorial 5K',
  array['5K'],
  'trail',
  'Billingham',
  '',
  'North East',
  'listed',
  array['racebest','https://racebest.com/races/uv5t4'],
  false,
  'GB',
  null
),
(
  '2026-11-25-leeds-5k-nov',
  '2026-11-25',
  'Leeds 5K',
  array['5K'],
  'road',
  'Leeds',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/64t79'],
  true,
  'GB',
  null
),
(
  '2026-12-06-chase-the-pud-10k',
  '2026-12-06',
  'Chase The Pud 10K',
  array['10K'],
  'road',
  'York',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/svy93'],
  true,
  'GB',
  null
),
(
  '2026-12-06-chase-the-pud-3k',
  '2026-12-06',
  'Chase The Pud 3K',
  array['3K'],
  'road',
  'York',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/a79ag'],
  true,
  'GB',
  null
),
(
  '2026-12-13-bedale-santa-run',
  '2026-12-13',
  'Bedale Santa Run',
  array['5K'],
  'trail',
  'Bedale',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/6s63f'],
  true,
  'GB',
  null
),
(
  '2026-12-21-winter-solstice-strider',
  '2026-12-21',
  'Winter Solstice Strider',
  array['5K','10K'],
  'trail',
  'Bingley',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/8v6xt'],
  false,
  'GB',
  null
),
(
  '2026-12-28-ambles-revenge',
  '2026-12-28',
  'Ambles Revenge',
  array['8 mile'],
  'trail',
  'Oxspring',
  '',
  'Midlands',
  'listed',
  array['racebest','https://racebest.com/races/c448w'],
  false,
  'GB',
  null
),
(
  '2026-12-28-buntingford-year-end-10',
  '2026-12-28',
  'Buntingford Year End 10',
  array['10 mile'],
  'road',
  'Buntingford',
  '',
  'East',
  'listed',
  array['racebest','https://racebest.com/races/ktrta'],
  false,
  'GB',
  null
),
(
  '2026-12-28-coley-canter',
  '2026-12-28',
  'Coley Canter',
  array['7.7 mile'],
  'trail',
  'Northowram',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/r5wfu'],
  false,
  'GB',
  null
),
(
  '2027-01-03-brampton-trail',
  '2027-01-03',
  'Brampton Trail Run',
  array['7K'],
  'trail',
  'Brampton',
  '',
  'North West',
  'listed',
  array['racebest','https://racebest.com/races/s5692'],
  false,
  'GB',
  null
),
(
  '2027-02-06-rombalds-stride',
  '2027-02-06',
  'Rombalds Stride',
  array['Ultra'],
  'trail',
  'Guiseley',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/h5e4v'],
  true,
  'GB',
  null
),
(
  '2027-02-13-billing-trail',
  '2027-02-13',
  'The Billing Trail Race',
  array['14K'],
  'trail',
  'Rawdon',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/w77ch'],
  true,
  'GB',
  null
),
(
  '2027-03-07-keighley-10k-5k',
  '2027-03-07',
  'Keighley 10k & 5k',
  array['5K','10K'],
  'trail',
  'Keighley',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/gc4he'],
  true,
  'GB',
  null
),
(
  '2027-03-14-wakefield-hospice-5k',
  '2027-03-14',
  'Wakefield Hospice 5K',
  array['5K'],
  'road',
  'Wakefield',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/f5vv7'],
  true,
  'GB',
  null
),
(
  '2027-03-14-wakefield-hospice-10k',
  '2027-03-14',
  'Wakefield Hospice 10K',
  array['10K'],
  'road',
  'Wakefield',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/4z7fr'],
  true,
  'GB',
  null
),
(
  '2027-03-14-thirsk-10',
  '2027-03-14',
  'Thirsk 10',
  array['10 mile'],
  'road',
  'Thirsk',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/r7499'],
  true,
  'GB',
  null
),
(
  '2027-03-14-st-michaels-harrogate',
  '2027-03-14',
  'Saint Michael''s Harrogate 10K & 5K',
  array['5K','10K'],
  'trail',
  'Harrogate',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/e4cta'],
  true,
  'GB',
  null
),
(
  '2027-03-21-buttermere-trail',
  '2027-03-21',
  'Buttermere Trail Race',
  array['20K'],
  'trail',
  'Buttermere',
  '',
  'North West',
  'listed',
  array['racebest','https://racebest.com/races/h6zx4'],
  false,
  'GB',
  null
),
(
  '2027-05-09-ripon-10-mile',
  '2027-05-09',
  'Ripon 10 Mile',
  array['10 mile'],
  'trail',
  'Ripon',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/63vtr'],
  true,
  'GB',
  null
),
(
  '2027-05-16-burton-leonard-10k',
  '2027-05-16',
  'Burton Leonard 10K',
  array['10K'],
  'trail',
  'Burton Leonard',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/5vq49'],
  true,
  'GB',
  null
),
(
  '2027-05-30-northallerton-10k',
  '2027-05-30',
  'Northallerton 10K',
  array['10K'],
  'road',
  'Northallerton',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/ts634'],
  true,
  'GB',
  null
),
(
  '2027-06-13-bedale-bolt',
  '2027-06-13',
  'Bedale Bolt 10K',
  array['10K'],
  'road',
  'Bedale',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/thx4w'],
  true,
  'GB',
  null
),
(
  '2027-06-21-solstice-saunter',
  '2027-06-21',
  'Solstice Saunter',
  array['5 mile'],
  'trail',
  'Bolton Abbey',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/zakxs'],
  true,
  'GB',
  null
),
(
  '2027-06-27-lindley-10k',
  '2027-06-27',
  'Lindley 10K',
  array['10K'],
  'road',
  'Lindley',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/3yzht'],
  true,
  'GB',
  null
),
(
  '2027-07-04-run-harrogate-10k',
  '2027-07-04',
  'Harmony Energy Run Harrogate 10K',
  array['10K'],
  'trail',
  'Harrogate',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/4v65g'],
  true,
  'GB',
  null
),
(
  '2027-08-22-scafell-pike-trail-marathon',
  '2027-08-22',
  'Scafell Pike Trail Marathon',
  array['Ultra'],
  'trail',
  'Keswick',
  '',
  'North West',
  'listed',
  array['racebest','https://racebest.com/races/zusvu'],
  false,
  'GB',
  null
),
(
  '2027-08-22-borrowdale-trail-half',
  '2027-08-22',
  'Borrowdale Trail Half Marathon',
  array['Half'],
  'trail',
  'Keswick',
  '',
  'North West',
  'listed',
  array['racebest','https://racebest.com/races/7wfe6'],
  false,
  'GB',
  null
),
(
  '2027-09-19-wetherby-10k',
  '2027-09-19',
  'Wetherby 10K',
  array['10K'],
  'trail',
  'Wetherby',
  '',
  'Yorkshire',
  'listed',
  array['racebest','https://racebest.com/races/uq93h'],
  true,
  'GB',
  null
)
on conflict (id) do update set
  sources = (
    select array_agg(distinct s)
    from unnest(coalesce(public.races.sources, '{}') || excluded.sources) as s
  );
