import type {
  AvatarSpec,
  CatalogRace,
  Distance,
  Friend,
  Persisted,
  SeasonEntry,
  Status,
  Surface,
} from "./types";

export const USER = {
  name: "Alex",
  city: "York",
  country: "GB",
  avatar: {
    initials: "AX",
    bg: "#1F1E18",
    fg: "#D6FF2E",
    shape: "squircle",
    pattern: "ring",
  } satisfies AvatarSpec,
};

export const DISTANCES: { id: Distance; label: string }[] = [
  { id: "5k", label: "5K" },
  { id: "10k", label: "10K" },
  { id: "10mile", label: "10 mile" },
  { id: "half", label: "Half" },
  { id: "marathon", label: "Marathon" },
  { id: "ultra", label: "Ultra" },
  { id: "other", label: "Other" },
];

export const SURFACES: { id: Surface; label: string }[] = [
  { id: "road", label: "Road" },
  { id: "trail", label: "Trail" },
];

export const STATUSES: { id: Status; label: string }[] = [
  { id: "thinking", label: "Thinking" },
  { id: "signed_up", label: "Signed up" },
  { id: "training", label: "Training" },
  { id: "done", label: "Done" },
];

export const COUNTRIES: { id: string; label: string }[] = [
  { id: "GB", label: "UK" },
  { id: "US", label: "USA" },
  { id: "DE", label: "Germany" },
  { id: "ES", label: "Spain" },
  { id: "DK", label: "Denmark" },
  { id: "FR", label: "France" },
];

export const CATALOG: CatalogRace[] = [
  {
    seriesId: "national-xc",
    name: "National Cross Country",
    city: "London",
    country: "GB",
    month: 2,
    day: 21,
    distance: "10k",
    surface: "trail",
  },
  {
    seriesId: "reading-half",
    name: "Reading Half Marathon",
    city: "Reading",
    country: "GB",
    month: 3,
    day: 1,
    distance: "half",
    surface: "road",
  },
  {
    seriesId: "knavesmire-5k",
    name: "Knavesmire 5K",
    city: "York",
    country: "GB",
    month: 3,
    day: 14,
    distance: "5k",
    surface: "road",
  },
  {
    seriesId: "bath-half",
    name: "Bath Half",
    city: "Bath",
    country: "GB",
    month: 3,
    day: 15,
    distance: "half",
    surface: "road",
  },
  {
    seriesId: "folkestone-10",
    name: "Folkestone 10",
    city: "Folkestone",
    country: "GB",
    month: 3,
    day: 29,
    distance: "10mile",
    surface: "road",
  },
  {
    seriesId: "london-landmarks-half",
    name: "London Landmarks Half",
    city: "London",
    country: "GB",
    month: 4,
    day: 5,
    distance: "half",
    surface: "road",
  },
  {
    seriesId: "brighton-marathon",
    name: "Brighton Marathon",
    city: "Brighton",
    country: "GB",
    month: 4,
    day: 12,
    distance: "marathon",
    surface: "road",
  },
  {
    seriesId: "manchester-marathon",
    name: "Manchester Marathon",
    city: "Manchester",
    country: "GB",
    month: 4,
    day: 12,
    distance: "marathon",
    surface: "road",
  },
  {
    seriesId: "boston-marathon",
    name: "Boston Marathon",
    city: "Boston",
    country: "US",
    month: 4,
    day: 20,
    distance: "marathon",
    surface: "road",
  },
  {
    seriesId: "london-marathon",
    name: "TCS London Marathon",
    city: "London",
    country: "GB",
    month: 4,
    day: 26,
    distance: "marathon",
    surface: "road",
  },
  {
    seriesId: "ultra-trail-snowdonia",
    name: "Ultra-Trail Snowdonia",
    city: "Llanberis",
    country: "GB",
    month: 5,
    day: 9,
    distance: "ultra",
    surface: "trail",
  },
  {
    seriesId: "leeds-half",
    name: "Leeds Half Marathon",
    city: "Leeds",
    country: "GB",
    month: 5,
    day: 10,
    distance: "half",
    surface: "road",
  },
  {
    seriesId: "north-downs-way-50",
    name: "North Downs Way 50",
    city: "Farnham",
    country: "GB",
    month: 5,
    day: 16,
    distance: "ultra",
    surface: "trail",
  },
  {
    seriesId: "manchester-half",
    name: "Manchester Half",
    city: "Manchester",
    country: "GB",
    month: 5,
    day: 17,
    distance: "half",
    surface: "road",
  },
  {
    seriesId: "edinburgh-marathon",
    name: "Edinburgh Marathon",
    city: "Edinburgh",
    country: "GB",
    month: 5,
    day: 24,
    distance: "marathon",
    surface: "road",
  },
  {
    seriesId: "vitality-london-10000",
    name: "Vitality London 10,000",
    city: "London",
    country: "GB",
    month: 5,
    day: 25,
    distance: "10k",
    surface: "road",
  },
  {
    seriesId: "south-downs-way-50",
    name: "South Downs Way 50",
    city: "Eastbourne",
    country: "GB",
    month: 6,
    day: 13,
    distance: "ultra",
    surface: "trail",
  },
  {
    seriesId: "roundhay-5k",
    name: "Roundhay 5K",
    city: "Leeds",
    country: "GB",
    month: 6,
    day: 20,
    distance: "5k",
    surface: "road",
  },
  {
    seriesId: "snowdonia-trail-marathon",
    name: "Snowdonia Trail Marathon",
    city: "Llanberis",
    country: "GB",
    month: 7,
    day: 18,
    distance: "marathon",
    surface: "trail",
  },
  {
    seriesId: "lakeland-50",
    name: "Lakeland 50",
    city: "Coniston",
    country: "GB",
    month: 7,
    day: 25,
    distance: "ultra",
    surface: "trail",
  },
  {
    seriesId: "york-10k",
    name: "York 10K",
    city: "York",
    country: "GB",
    month: 8,
    day: 2,
    distance: "10k",
    surface: "road",
  },
  {
    seriesId: "utmb",
    name: "UTMB",
    city: "Chamonix",
    country: "FR",
    month: 8,
    day: 28,
    distance: "ultra",
    surface: "trail",
  },
  {
    seriesId: "keswick-trail-10k",
    name: "Keswick Trail 10K",
    city: "Keswick",
    country: "GB",
    month: 9,
    day: 5,
    distance: "10k",
    surface: "trail",
  },
  {
    seriesId: "hardmoors-60",
    name: "Hardmoors 60",
    city: "Guisborough",
    country: "GB",
    month: 9,
    day: 12,
    distance: "ultra",
    surface: "trail",
  },
  {
    seriesId: "great-north-run",
    name: "Great North Run",
    city: "Newcastle",
    country: "GB",
    month: 9,
    day: 13,
    distance: "half",
    surface: "road",
  },
  {
    seriesId: "copenhagen-half",
    name: "Copenhagen Half",
    city: "Copenhagen",
    country: "DK",
    month: 9,
    day: 20,
    distance: "half",
    surface: "road",
  },
  {
    seriesId: "berlin-marathon",
    name: "BMW Berlin Marathon",
    city: "Berlin",
    country: "DE",
    month: 9,
    day: 27,
    distance: "marathon",
    surface: "road",
  },
  {
    seriesId: "great-scottish-run",
    name: "Great Scottish Run",
    city: "Glasgow",
    country: "GB",
    month: 9,
    day: 27,
    distance: "half",
    surface: "road",
  },
  {
    seriesId: "kielder-marathon",
    name: "Kielder Marathon",
    city: "Kielder",
    country: "GB",
    month: 10,
    day: 4,
    distance: "marathon",
    surface: "trail",
  },
  {
    seriesId: "chicago-marathon",
    name: "Chicago Marathon",
    city: "Chicago",
    country: "US",
    month: 10,
    day: 11,
    distance: "marathon",
    surface: "road",
  },
  {
    seriesId: "royal-parks-half",
    name: "Royal Parks Half",
    city: "London",
    country: "GB",
    month: 10,
    day: 11,
    distance: "half",
    surface: "road",
  },
  {
    seriesId: "yorkshire-marathon",
    name: "Yorkshire Marathon",
    city: "York",
    country: "GB",
    month: 10,
    day: 18,
    distance: "marathon",
    surface: "road",
  },
  {
    seriesId: "nyc-marathon",
    name: "TCS New York City Marathon",
    city: "New York",
    country: "US",
    month: 11,
    day: 1,
    distance: "marathon",
    surface: "road",
  },
  {
    seriesId: "york-frost-5k",
    name: "York Christmas Cracker 5K",
    city: "York",
    country: "GB",
    month: 12,
    day: 6,
    distance: "5k",
    surface: "road",
  },
  {
    seriesId: "valencia-marathon",
    name: "Valencia Marathon",
    city: "Valencia",
    country: "ES",
    month: 12,
    day: 6,
    distance: "marathon",
    surface: "road",
  },
];

function entry(
  seriesId: string,
  year: number,
  status: Status,
  notes = "",
  finishTime?: string
): SeasonEntry {
  return {
    key: `${seriesId}:${year}`,
    seriesId,
    year,
    status,
    notes,
    finishTime,
  };
}

export const FRIENDS: Friend[] = [
  {
    id: "sam",
    name: "Sam",
    city: "Leeds",
    avatar: {
      initials: "SM",
      bg: "#2A3A4A",
      fg: "#D7E7F5",
      shape: "circle",
      pattern: "split",
    },
    season: [
      entry("manchester-half", 2026, "signed_up", "Trying to break 1:40."),
      entry("london-marathon", 2026, "training", "Charity place. Long runs on canal."),
    ],
  },
  {
    id: "priya",
    name: "Priya",
    city: "York",
    avatar: {
      initials: "PR",
      bg: "#4A2C24",
      fg: "#F3C7B5",
      shape: "hex",
      pattern: "dot",
    },
    season: [
      entry("york-10k", 2026, "signed_up", "Home course. Hang on to 4:05s."),
      entry(
        "snowdonia-trail-marathon",
        2026,
        "training",
        "First proper mountain day."
      ),
    ],
  },
  {
    id: "jordan",
    name: "Jordan",
    city: "Sheffield",
    avatar: {
      initials: "JD",
      bg: "#24352A",
      fg: "#C5E3C0",
      shape: "diamond",
      pattern: "bars",
    },
    season: [
      entry("lakeland-50", 2026, "signed_up", "Recce the climbs in June."),
      entry("hardmoors-60", 2026, "thinking", "If the legs recover."),
    ],
  },
  {
    id: "mei",
    name: "Mei",
    city: "Manchester",
    avatar: {
      initials: "ME",
      bg: "#3A2448",
      fg: "#E4C8F5",
      shape: "shield",
      pattern: "ring",
    },
    season: [
      entry("manchester-half", 2026, "signed_up", "Home half. Pacing Sam."),
      entry("yorkshire-marathon", 2026, "signed_up", "Train together?"),
    ],
  },
  {
    id: "chris",
    name: "Chris",
    city: "Hull",
    avatar: {
      initials: "CH",
      bg: "#2C2A24",
      fg: "#C9C2B2",
      shape: "squircle",
      pattern: "solid",
    },
    season: [],
  },
];

export const SAMPLE_SEASON: SeasonEntry[] = [
  entry(
    "manchester-half",
    2026,
    "signed_up",
    "Long-run dress rehearsal for autumn."
  ),
  entry("york-10k", 2026, "signed_up", "PB hunt. Hang at 4:00/km through 7k."),
  entry(
    "yorkshire-marathon",
    2026,
    "thinking",
    "Ballot / charity place still open."
  ),
  entry("york-frost-5k", 2026, "done", "Icy but honest.", "21:48"),
];

export function emptyState(): Persisted {
  return {
    version: 2,
    name: "",
    city: "",
    year: 2026,
    units: "km",
    customRaces: [],
    season: [],
  };
}
